### ISSUE TITLE
Workflow failure: Could not resolve to a PullRequest with the number of 0

### ISSUE THREAD

**Issue by garaujodev** [agilepathway/label-checker#392] opened 2023-09-06 12:39 UTC
I'm getting consecutive failures in the workflow. This is my output:

```
Checking GitHub labels ...
2023/09/06 12:23:33 Error that we cannot handle, Could not resolve to a PullRequest with the number of 0.
```

## My workflow file

```
name: Label checker
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: fix,feature,build,documentation,refactor,chore,style,test,performance,revert
          none_of: blocked
          repo_token: ${{ secrets.GITHUB_TOKEN }}
```

Any ideas?

**Comment by johnboyes** [comment] 2023-09-06 16:43
Hi @garaujodev, thanks for raising this.  I suspect this was inadvertently caused by [v1.5.0](https://github.com/agilepathway/label-checker/releases/tag/v1.5.0) which was released last week.  I'm about to go on holiday for a week, so as I don't have time to find the proper fix before I go I'll revert that change in a new release, working on that right now.

**Comment by johnboyes** [comment] 2023-09-06 16:56
Done, I have created a new release [v1.5.4](https://github.com/agilepathway/label-checker/releases/tag/v1.5.4) which reverts the suspect [v1.5.0](https://github.com/agilepathway/label-checker/releases/tag/v1.5.0) change.  @garaujodev please confirm that this has fixed things for you, thanks.

**Comment by piotrekkr** [comment] 2023-09-07 08:49
@garaujodev Can you tell what kind of event type it is exactly that is generating this error? It works for me for `pull_request_review` and also `pull_request`.

![image](https://github.com/agilepathway/label-checker/assets/503782/fbeaea0a-88e2-45aa-a98c-e831a27a58c5)

My workflow looks like this:
```yaml
name: Check labels

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-labels:
    name: Check PR labels
    runs-on: ubuntu-22.04
    steps:
      - name: Golden master label validation
        uses: docker://agilepathway/pull-request-label-checker:v1.5.0
        with:
          one_of: golden-master-validated
          none_of: do-not-merge
          repo_token: ${{ secrets.GITHUB_TOKEN }}
```

//EDIT 

Also checked with `latest` version and it works too.

**Comment by piotrekkr** [comment] 2023-09-12 07:53
@garaujodev Thanks for reply. I think `workflow_run` event may not provide accurate PR data. Here is [event payload described](https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run) and I can see it has `pull_requests` key containing *array* of pull requests. `workflow_run` event [may be triggered by variety of events](https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run) and may or may not contain `pull_requests` key in payload for example when triggering workflow run was started by `push` event on `main` branch. It would fail even without my change with `pull_request_review` fix. 

In theory this action could try to check:
- if exist: `github.event.pull_request` then use this
- if exist: `github.event.workflow_run.pull_requests[0]` then use this 

But this seems a little hackish.

If this label check should only work with pull requests events then you should use

```
on:
  pull_request:
    ...
```

**Comment by johnboyes** [comment] 2023-09-12 18:12
Thanks for looking into this so thoroughly, @piotrekkr, and for providing the additional info above, @garaujodev.  I agree with @piotrekkr's proposal to always use the `pull_request` event and never use the `workflow_run` event  when using this label checker.  If that sounds ok to you both then the only action I now need to take is a new release reinstating [the functionality that I reverted as a precaution last week](https://github.com/agilepathway/label-checker/releases/tag/v1.5.4).

**Comment by johnboyes** [comment] 2023-09-13 18:37
> the only action I now need to take is a new release reinstating [the functionality that I reverted as a precaution last week](https://github.com/agilepathway/label-checker/releases/tag/v1.5.4).

This is now done, in #400.  I'll close this issue now, thanks again to both of you, @piotrekkr and @garaujodev for the thorough investigation 🙏🏻

**Closed by johnboyes** 2023-09-13 18:37 UTC
